server:
  port: 8084

spring:
  profiles:
    active: core-prd, student
  application:
    name: service-student

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8081/eureka/

ribbon:
  eureka:
    enabled: true

#lcn分布式事务
tx-lcn:
  client:
    manager-address: 192.168.0.115:8070
  springcloud:
    loadbalance:
      enabled: true
