# swagger配置
swagger:
  enabled: true
  api-info:
    appName: 'icloud-admin-api'
    title: 'icloud-admin-api'
    description: '后台管理员接口服务'
    license: ''
    license-url: ''
    version: 'v1.0'
    contact-name: 'icloud-admin'
    #    contact-url: 'https://coding.net/u/zhuchuangang/p/thor/git'
    contact-email: ''
    #    terms-of-service-url: 'https://coding.net/u/zhuchuangang/p/thor/git'
    base-package: com.project.icloud.rest
    oauth:
      clientId: test
      clientSecret: test
      access-token-uri: http://127.0.0.1:7777/uaa/oauth/token
      user-authorization-uri: http://127.0.0.1:7777/uaa/oauth/authorize

# 数据库配置
spring:
  datasource:
    url: jdbc:mysql://119.3.43.44:3306/idrive?useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true&serverTimezone=GMT%2B8
    username: root
    password: dhgh123456
    driver-class-name: com.mysql.jdbc.Driver


# mybatis配置
mybatis-plus:
  # 如果是放在src/main/java目录下 classpath:/com/yourpackage/*/mapper/*Mapper.xml
  # 如果是放在resource目录 classpath:/mapper/*Mapper.xml
  mapper-locations: classpath:/mapper/*Mapper.xml
  #实体扫描，多个package用逗号或者分号分隔
  typeAliasesPackage: com.project.icloud.dao.domain
  global-config:
    #主键类型  0:"数据库ID自增", 1:"用户输入ID",2:"全局唯一ID (数字类型唯一ID)", 3:"全局唯一ID UUID";
    id-type: 0
    #字段策略 0:"忽略判断",1:"非 NULL 判断"),2:"非空判断"
    field-strategy: 2
    #驼峰下划线转换
    db-column-underline: true
    #刷新mapper 调试神器
    #refresh-mapper: true
    #数据库大写下划线转换
    capital-mode: false
    # Sequence序列接口实现类配置
    #key-generator: com.baomidou.mybatisplus.incrementer.OracleKeyGenerator
    #逻辑删除配置（下面3个配置）
    logic-delete-value: 1
    logic-not-delete-value: 0
    sql-injector: com.baomidou.mybatisplus.mapper.LogicSqlInjector
    #自定义填充策略接口实现
    #meta-object-handler: com.baomidou.springboot.MyMetaObjectHandler
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false
    #配置JdbcTypeForNull
    jdbc-type-for-null: 'null'
#  logging:
#    level:
#      root:  ERROR
#      org.springframework:  ERROR
#      org.mybatis:  ERROR
#      org.linlinjava.litemall.db:  DEBUG
