#微信配置
weixin:
  jscode2session: https://api.weixin.qq.com/sns/jscode2session
  #公众号
  subscription:
    app_id: 111111111111
    app_secret: 1111111111111
    #微信支付回调地址
    order_notify_url: orderPayCallBack
    enterprice_url:
    refund_url:
  #学员端
  student:
    app_id: stu123
    app_secret: 22222222222222
    #微信支付回调地址
    order_notify_url: orderPayCallBack
    enterprice_url:
    refund_url:
  #教练端
  coach:
    app_id: 333333333
    app_secret: 33333333333
  #商户号
  cert_path: 44444444444
  mch_id: 4444444444
  key: 44444444444
  httpConnectTimeoutMs: 8000
  httpReadTimeoutMs: 10000
  recharge_notify_url: 44444444444

#聚合SMS配置
sms:
  connTimeOut: 30000
  readTimeOut: 30000
  userAgent: "Mozilla/5.0 (Windows NT 6.1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/29.0.1547.66 Safari/537.36"
  appKey: 13213245
  overTime: 5
  tplId:
    register: 180142
